export const projects = [
  {
    id: "cascading-ai",
    name: "Cascading AI (YC23) • AI-native loan origination platform",
    url: "",
    linkWord: "",
  },
  {
    id: "valkyrie-ai",
    name: "Valkyrie AI • LLMs + Knowledge Graphs product",
    url: "",
    linkWord: "",
  },
  {
    id: "dotearth",
    name: "dotEARTH • Generative AI venture studio",
    url: "https://x.com/8BIT/status/1820462652499410980",
    linkWord: "Generative",
  },
  {
    id: "supportlogic",
    name: "SupportLogic • Enterprise AI/ML/NLP products",
    url: "https://x.com/8BIT/status/1820462645847470140",
    linkWord: "Enterprise",
  },
  {
    id: "healme",
    name: "Heal.me • Automated SaaS marketplace platform",
    url: "https://x.com/8BIT/status/1820462639765389508",
    linkWord: "Automated",
  },
  {
    id: "meera-health",
    name: "Meera Health • AI-powered clinical trials marketplace",
    url: "https://x.com/8BIT/status/1820462633264226688",
    linkWord: "clinical",
  },
  {
    id: "sats-app",
    name: "Sats App • Nigeria's first USDC mobile neobank",
    url: "https://x.com/8BIT/status/1820462619641483654",
    linkWord: "USDC",
  },
  {
    id: "btc-jobs",
    name: "BTC Jobs • Job board for bitcoiners",
    url: "https://x.com/8BIT/status/1818090371743703226",
    linkWord: "bitcoiners",
  },
  {
    id: "btc-email",
    name: "BTC.email • Bitcoin email without spam",
    url: "https://x.com/8BIT/status/1816094310879666193",
    linkWord: "Bitcoin",
  },
  {
    id: "trading-bitcoin",
    name: "Trading Bitcoin • Newsletter on bitcoin trading",
    url: "https://x.com/8BIT/status/1819107576640155649",
    linkWord: "Newsletter",
  },
  {
    id: "yen",
    name: "YEN • Social crypto meta exchange",
    url: "https://x.com/8BIT/status/1819239219119718768",
    linkWord: "crypto",
  },
  {
    id: "pinpoint",
    name: "Pinpoint • Engineering insights platform (acquired)",
    url: "https://x.com/8BIT/status/1817666142720217113",
    linkWord: "acquired",
  },
  {
    id: "try-george",
    name: "Try George • To-Do app for iOS",
    url: "https://x.com/8BIT/status/1816102242983829574",
    linkWord: "To-Do",
  },
  {
    id: "desk",
    name: "Desk • Award-winning writing app for macOS",
    url: "https://x.com/8BIT/status/1815923219515461851",
    linkWord: "Award-winning",
  },
  {
    id: "mnml",
    name: "MNML • Desktop app for Medium.com",
    url: "https://x.com/8BIT/status/1817572268882690511",
    linkWord: "Desktop",
  },
  { id: "youtube", name: "YouTube • Multi-channel daily vlog/livestream", url: "", linkWord: "" },
  {
    id: "blog",
    name: "Blog & Newsletters • 20+ years of daily writing",
    url: "https://www.freecodecamp.org/news/a-simple-content-marketing-playbook-for-software-developers-and-creators-937f86d6dd90",
    linkWord: "daily",
  },
  {
    id: "up2398",
    name: "UP2398 • Entrepreneur in Residence",
    url: "https://x.com/8BIT/status/1817666139645693965",
    linkWord: "Entrepreneur",
  },
  {
    id: "eve",
    name: "EVE • Slackbot automating HR",
    url: "https://x.com/8BIT/status/1817656656513380415",
    linkWord: "Slackbot",
  },
  {
    id: "teeny-tokyo",
    name: "Teeny Tokyo • Image editing app for macOS",
    url: "https://x.com/8BIT/status/1816083144937713779",
    linkWord: "Image",
  },
  {
    id: "learn-capital",
    name: "Learn Capital • Advisor & technical diligence",
    url: "",
    linkWord: "",
  },
  { id: "projector", name: "Projector • Mobile notifications & analytics", url: "", linkWord: "" },
  { id: "geneva-capital", name: "Geneva Capital • Fundraising advisor", url: "", linkWord: "" },
  { id: "zesty", name: "Zesty • YC '14, COO/PeopleOps", url: "", linkWord: "" },
  { id: "assembly", name: "Assembly • YC '13, COO/Product", url: "", linkWord: "" },
  {
    id: "iron-yard",
    name: "The Iron Yard • Largest US coding bootcamp (acquired)",
    url: "https://x.com/8BIT/status/1818619431255146685",
    linkWord: "coding",
  },
  {
    id: "pressgram",
    name: "Pressgram • Kickstarter-funded iOS photo app",
    url: "https://x.com/8BIT/status/1818384132113908070",
    linkWord: "Kickstarter-funded",
  },
  {
    id: "8bit",
    name: "8BIT • WordPress themes & content network",
    url: "https://x.com/8BIT/status/1818325223386558577",
    linkWord: "WordPress",
  },
  {
    id: "action-influence",
    name: "Action & Influence • Team performance tool",
    url: "https://x.com/8BIT/status/1818405163058524242",
    linkWord: "performance",
  },
  {
    id: "chairco",
    name: "ChairCo • Professional coaching",
    url: "https://x.com/8BIT/status/1818400895094116652",
    linkWord: "coaching",
  },
  {
    id: "web-hosting-dummies",
    name: "Web Hosting for Dummies • Technical Editor",
    url: "https://x.com/8BIT/status/1819752821190959239",
    linkWord: "Technical",
  },
  {
    id: "churchcrunch",
    name: "ChurchCrunch • #1 tech blog for churches",
    url: "https://x.com/8BIT/status/1817229889101070394",
    linkWord: "churches",
  },
  { id: "boosterthon", name: "BoosterThon • CTO & special projects", url: "", linkWord: "" },
  {
    id: "blogcheck",
    name: "BlogCheck • Server monitoring (acquired)",
    url: "https://x.com/8BIT/status/1816929921349870079",
    linkWord: "monitoring",
  },
  {
    id: "twitch-tech",
    name: "Twitch Technologies • Alternative keyboard CTO",
    url: "https://x.com/8BIT/status/1816532221760503826",
    linkWord: "keyboard",
  },
  {
    id: "sochurch",
    name: "SoChurch • B2B SaaS for churches",
    url: "https://x.com/8BIT/status/1816929924051280035",
    linkWord: "SaaS",
  },
  {
    id: "beaconads",
    name: "BeaconAds • Niche ad network (acquired)",
    url: "https://x.com/8BIT/status/1816929918447730715",
    linkWord: "ad",
  },
  {
    id: "church-analytics",
    name: "Church Analytics • Real-time analytics (acquired)",
    url: "https://x.com/8BIT/status/1816929914643448152",
    linkWord: "analytics",
  },
  {
    id: "milk-engine",
    name: "Milk Engine • Web consulting & strategy",
    url: "https://x.com/8BIT/status/1818345522911985846",
    linkWord: "Web",
  },
  {
    id: "north-point",
    name: "North Point Ministries • Creative Director",
    url: "https://x.com/8BIT/status/1816569148933083461",
    linkWord: "Creative",
  },
  {
    id: "gospelr",
    name: "Gospelr • Christian Twitter app (acquired)",
    url: "https://x.com/8BIT/status/1816896384185831508",
    linkWord: "Twitter",
  },
  {
    id: "datecraft",
    name: "DateCraft • Dating site for WoW players (acquired)",
    url: "https://x.com/8BIT/status/1816890221889233089",
    linkWord: "WoW",
  },
  {
    id: "second-adoption",
    name: "Second Adoption Media • Social network for adoptees",
    url: "https://x.com/8BIT/status/1816890216747028983",
    linkWord: "adoptees",
  },
  {
    id: "fox-newscorp",
    name: "Fox/NewsCorp • Executive Product Director",
    url: "https://www.christiancentury.org/article/2007-12/beliefnet-acquired-fox-media-empire",
    linkWord: "Executive",
  },
  {
    id: "dell",
    name: "Dell Inc. • Engineer & Product Manager",
    url: "https://x.com/8BIT/status/1816588323680362932",
    linkWord: "Engineer",
  },
  { id: "lords-church", name: "Lord's Church • Youth Pastor", url: "", linkWord: "" },
  { id: "life-multimedia", name: "Life Multimedia • Web design agency", url: "", linkWord: "" },
  { id: "starbucks", name: "Starbucks • Part-time Barista", url: "", linkWord: "" },
  { id: "fedex", name: "FedEx/Kinkos • Copier & paper boy", url: "", linkWord: "" },
  {
    id: "patient-care",
    name: "Patient Care Technologies • Network engineer",
    url: "",
    linkWord: "",
  },
  { id: "internap", name: "Internap • NOC engineer (CCNA/CCDA)", url: "", linkWord: "" },
  {
    id: "georgia-tech",
    name: "Georgia Tech • Various tech & teaching roles",
    url: "",
    linkWord: "",
  },
  {
    id: "johnson-johnson",
    name: "Johnson & Johnson • Web tools for Acuvue.com",
    url: "",
    linkWord: "",
  },
  { id: "publix", name: "Publix • Bag boy to stock to cart retrieval", url: "", linkWord: "" },
  { id: "josephs-pizza", name: "Joseph's Pizza • Cashier & waiter", url: "", linkWord: "" },
  { id: "js-computer", name: "JS Computer Repair • Fixed SMB computers", url: "", linkWord: "" },
  { id: "boars-head", name: "Boar's Head Deli • Prep & serve", url: "", linkWord: "" },
  { id: "pakmail", name: "PakMail • Cashier & packager", url: "", linkWord: "" },
  { id: "panera", name: "Panera Bread • Prep cook & dishwasher", url: "", linkWord: "" },
  {
    id: "melkior",
    name: "Melkior Design • First company! HTML & Flash games",
    url: "",
    linkWord: "",
  },
] as const

export const education = [
  {
    id: "dallas-seminary",
    name: "Dallas Seminary • Masters in Education & Biblical Studies",
    url: "https://x.com/8BIT/status/1817294117761691785",
    linkWord: "Masters",
  },
  {
    id: "prepare-enrich",
    name: "Prepare/Enrich • Certified marriage counseling",
    url: "https://x.com/8BIT/status/1817294120794099927",
    linkWord: "Certified",
  },
  {
    id: "georgia-tech",
    name: "Georgia Tech • B.S. Science, Technology & Culture",
    url: "https://x.com/8BIT/status/1817577662715396497",
    linkWord: "Culture",
  },
  {
    id: "bolles",
    name: "The Bolles School • Senior quote: Kaizen",
    url: "https://www.investopedia.com/terms/k/kaizen.asp",
    linkWord: "Kaizen",
  },
  {
    id: "asij",
    name: "American School in Japan • Where I fell in love with the internet",
    url: "",
    linkWord: "",
  },
] as const

export const volunteer = [
  {
    id: "mentor-blue",
    name: "Mentor, Blue Startups • Helping entrepreneurs win",
    url: "",
    linkWord: "",
  },
  {
    id: "coach-uh",
    name: "Coach/Speaker, University of Hawai'i • Challenging engineers",
    url: "https://sa2020.org/stories/getting-your-code-on",
    linkWord: "Challenging",
  },
  {
    id: "soccer-coach",
    name: "Soccer Coach • US Soccer Federation Licensed",
    url: "https://x.com/8BIT/status/1817289302155419802",
    linkWord: "Licensed",
  },
  {
    id: "youth-pastor",
    name: "Youth Pastor • Preached & mentored 50+ community",
    url: "",
    linkWord: "",
  },
  {
    id: "tek-styles",
    name: "TEK Styles • Hip-hop and breakdance instructor",
    url: "",
    linkWord: "",
  },
  {
    id: "defy-ventures",
    name: "Defy Ventures • Coach for Entrepreneurs in Training",
    url: "",
    linkWord: "",
  },
] as const
